### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by vstrg** [3urobeat/steam-comment-service-bot#190] opened 2023-07-02 22:44 UTC
**Describe the bug**
I'm trying to use !upvote and !downvote but it throws an error

**Full error**
Sorry but an error occurred while loading the sharedfile you have provided: TypeError: Cannot read properties of undefined (reading 'trim')

**Additional context**
https://prnt.sc/t2hgijjoO8iZ

**Comment by 3urobeat** [comment] 2023-07-02 22:47
Hey, thanks for opening an issue!  
I have encountered this bug once before as well, it seems to be a bug in the SteamCommunity library.  
I will have to investigate further but I am thinking that this might be a translation issue as this specific function scrapes data directly from the Steam webpage and therefore relies on the English language.

**Comment by vstrg** [comment] 2023-07-03 02:58
Hey, thanks for answering.I found the issue because I send upvote and downvote from csgo vac banned accounts to csgo screenshot, but it doesn't give an error that you can't send from vac banned accounts on bot. I found out when I logged into my account and tried to upvote manually.

**Comment by 3urobeat** [comment] 2023-07-03 09:25
Oh, interesting, I didn't know that either. Thanks for letting me know!  
I'll take a look at it to improve the response.

**Comment by 3urobeat** [comment] 2023-07-04 14:45
I have made an experimental patch 8836b44 that should fix any issues caused by a translated page.  
I still think that this is the cause of this error. Your vac'ed account shouldn't be the reason why the page is not being parsed correctly.  

I sadly don't have any unlimited banned accounts that I could test voting with to implement another message atm.  

I'll keep this issue open until the fix is out on the master branch in version 2.12.5.

**Comment by vstrg** [comment] 2023-07-11 06:54
Hi again, I tried with version 2.12.5. !upvote and !downvote commands work without errors, but they are not sent to the csgo screenshot from accounts with csgo vac.

**Comment by elraennn** [comment] 2023-07-11 08:22
steam does not allow vac  accounts

**Comment by 3urobeat** [comment] 2023-07-11 08:25
Hey, that's good to know - thank you so much for the replies!  
I will check again if I can detect VAC banned accounts and exclude them from the list of bots for voting.  

Since the error is fixed now I'm going to close this issue. If this issue reoccurs don't hesitate do reopen it and if there is something else feel free to open another issue! :)

**Closed by 3urobeat** 2023-07-11 08:25 UTC
Labels: Bug, Enhancement
