### ISSUE TITLE
ㅤㅤㅤㅤ  

### ISSUE THREAD

**Issue by feadelgemz** [3urobeat/steam-comment-service-bot#226] opened 2023-12-27 14:20 UTC
**Describe the bug**
What happened?

**Full error**
Please post the **complete** error here!

**Additional context**
Please add any other information here if you have some.

**Comment by feadelgemz** [comment] 2023-12-27 14:22
I have a lot of game reviews. I want to boost them

**Comment by 3urobeat** [comment] 2023-12-27 14:23
Duplicate of #207?  
Review support will be implemented in v2.15

**Closed by 3urobeat** 2023-12-27 14:23 UTC
Labels: Bug

**Comment by 3urobeat** [comment] 2023-12-27 14:27
Thank you for the donation :heart:

**Comment by feadelgemz** [comment] 2023-12-29 09:43
@

**Comment by feadelgemz** [comment] 2023-12-29 09:43
❤
