### ISSUE TITLE
Bot hangs at startup after internet connection check

### ISSUE THREAD

**Issue by pushkinb** [3urobeat/steam-comment-service-bot#246] opened 2024-05-16 10:14 UTC
**Question or issue you are experiencing**
Please explain your question here. If you've got an error or something else related, then please include it here as well.

**Additional information**
Please add any other information here, if you have some.

![image](https://github.com/3urobeat/steam-comment-service-bot/assets/160387754/fb067184-5a1b-48a6-aff5-065e2aa6b31a)

**Comment by 3urobeat** [comment] 2024-05-21 18:06
Hey, sorry for the late response.  
This is weird, looks like it hangs at loading the DataManager, a component of the bot.

I'm honestly not sure how I'd be able to reproduce this issue. Are you still encountering it or has it fixed itself after a few restarts?

**Comment by pushkinb** [comment] 2024-05-22 11:18
hi, this problem was solved after reinstalling the program, so everything is fine. thanks for the answer

**Comment by 3urobeat** [comment] 2024-05-22 14:56
Alright, thanks for the feedback!  
I'm going to check it out either way, maybe I can find something.

**Comment by 3urobeat** [comment] 2024-10-12 13:43
I was just able to replicate this using a slow VPN connection.  
It seems like the bot is actually hanging at converting an owner vanity to a steamID64 in `processData()`. This is only accurately reflected in the log when having debug log messages enabled.  
I'll move (or add) an INFO log message to reflect the step the bot is actually at more clearly.

**Comment by 3urobeat** [comment] 2024-10-12 14:55
Ok, nope, sorry, I have no idea how this happened. 

I'm going to close this for now, if anyone encounters this issue again, please reopen.

**Closed by 3urobeat** 2024-10-12 14:55 UTC
Labels: Bug
